# Generated by Django 3.2.8 on 2021-10-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('tag', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='blog/')),
                ('desc', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('pub_time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pub_time'],
            },
        ),
    ]
